LIB=	obase
SRCS=   bsd_getopt.c setmode.c strtonum.c strlcpy.c getbsize.c user_from_uid.c \
 strmode.c fmt_scaled.c fgetln.c strlcat.c arc4random.c vis.c unvis.c \
 setpassent.c base64.c fparseln.c radixsort.c \
 md4.c md5.c rmd160.c sha1.c sha2.c \
 md4hl.c md5hl.c rmd160hl.c sha1hl.c sha256hl.c sha384hl.c sha512hl.c \
ohash_create_entry.c  ohash_enum.c             ohash_lookup_memory.c \
ohash_delete.c        ohash_init.c             ohash_qlookup.c \
ohash_do.c            ohash_interval.c         ohash_qlookupi.c \
ohash_entries.c       ohash_lookup_interval.c

.include <bsd.lib.mk>
